# Global settings applied to the whole site.
# “base” is directory to change to before starting build, and
# “publish” is the directory to publish (relative to root of your repo).
# “command” is your build command.

[build]
  base    = ""
  publish = "build"
  command = "yarn build"

# Production context: All deploys to the main
# repository branch will inherit these settings.

[context.production]
  command = "yarn build"

# Deploy Preview context: All Deploy Previews
# will inherit these settings.

[context.deploy-preview]
  command = "yarn build"

# Branch Deploy context: All deploys that are not in
# an active Deploy Preview will inherit these settings.

[context.branch-deploy]
  command = "yarn build"

[[redirects]]
  from   = "/*"
  to     = "/index.html"
  status = 200